[[cells]]
name = "pox-type.bc"
enable_type_id = false

  [cells.location]
  file = "/home/riyan/Downloads/Projects/ckbuilder/week-6/pox-type/dist/pox-type.bc"

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x5fb6d278633ead3acffdf85fd232a2be2af78156"
hash_type = "type"
